---
substitutions:
  baud_rate: 0
  rx_buffer_size: 0
  tx_buffer_size: 0
  meshmesh_channel: 6
  meshmesh_version: main

external_components:
  - source: /home/stefano/Sviluppo/Stefano/Meshmesh/workspace/esphome-meshmesh/components
    refresh: 0s

mdns:
  disabled: true

socket:
  implementation: meshmesh_esp8266

meshmesh:
  baud_rate: ${baud_rate}
  rx_buffer_size: ${rx_buffer_size}
  tx_buffer_size: ${tx_buffer_size}
  password: !secret meshmesh_password
  channel: ${meshmesh_channel}
  use_starpath: true
