---
substitutions:
  baud_rate: 0
  rx_buffer_size: 0
  tx_buffer_size: 0
  meshmesh_channel: 6
  meshmesh_version: main
  meshmesh_coordinator: false
  meshmesh_starpath: false

external_components:
  - source: github://EspMeshMesh/esphome-meshmesh@${meshmesh_version}

mdns:
  disabled: true

socket:
  implementation: meshmesh_esp8266

meshmesh:
  baud_rate: ${baud_rate}
  rx_buffer_size: ${rx_buffer_size}
  tx_buffer_size: ${tx_buffer_size}
  password: !secret meshmesh_password
  channel: ${meshmesh_channel}
  is_coordinator: ${meshmesh_coordinator}
  use_starpath: ${meshmesh_starpath}