---
substitutions:
  api_reboot_timeout: 15min
  logger_baud_rate: 115200
  logger_level: INFO

esphome:
  name: ${name}
  friendly_name: ${friendly_name}

ota:
  - platform: esphome
    id: ota_esphome

    port: 3232

api:
  reboot_timeout: ${api_reboot_timeout}
  #encryption:
  #  key: !secret api_encryption_key

logger:
  level: ${logger_level}
  baud_rate: ${logger_baud_rate}

time:
  - platform: homeassistant
    id: time_homeassistant

sensor: !include_dir_list common/sensors
binary_sensor: !include_dir_list common/binary_sensors
button: !include_dir_list common/buttons
