---
substitutions:

packages:
  base: !include common-base.yaml

esp32:
  board: esp32-c3-devkitm-1
  variant: ESP32C3
  framework:
    type: esp-idf

esphome:
  platformio_options:
    board_build.flash_mode: dio


