---
substitutions:
  name: coordinator
  friendly_name: Coordinator
  api_reboot_timeout: 0s
  baud_rate: 460800
  rx_buffer_size: 2048
  tx_buffer_size: 4096
  logger_level: INFO
  logger_baud_rate: 0
  meshmesh_channel: 6
  meshmesh_version: dev

packages:
  common: !include modules/devices/d1-mini.yaml

meshmesh:
  is_coordinator: true
  use_starpath: true

ping:
  address: server