---
substitutions:
  name: coordinator32
  friendly_name: Coordinator32
  api_reboot_timeout: 0s
  baud_rate: 460800
  rx_buffer_size: 2048
  tx_buffer_size: 4096
  logger_level: INFO
  logger_baud_rate: 0
  meshmesh_channel: 6

packages:
  common: !include modules/devices/esp32dev.yaml