---
substitutions:
  name: garage_door_1
  friendly_name: Garage Door 1
  api_reboot_timeout: 0s
  meshmesh_channel: 6
  open_duration: 13sec
  close_duration: 26sec

packages:
  common: !include modules/devices/shelly-1-cover.yaml
