---
substitutions:
  name: humidity-temperature
  friendly_name: Humidity Temperature
  meshmesh_channel: 6
  meshmesh_node_type: edge
  logger_hardware_uart: USB_CDC

packages:
  common: !include modules/devices/super-mini.yaml

deep_sleep:
  id: deep_sleep_1
  run_duration: 20s
  sleep_duration: 5min

switch:
  - platform: template
    id: deep_sleep_disable
    name: "Disable deep_sleep"
    restore_mode: ALWAYS_OFF
    optimistic: true
    turn_on_action:
      - deep_sleep.prevent: deep_sleep_1
#    turn_off_action:
#      - deep_sleep.enter: deep_sleep_1
  - platform: template
    id: deep_sleep_enable
    name: "Enable deep_sleep"
    restore_mode: ALWAYS_OFF
    optimistic: true
    turn_on_action:
      - deep_sleep.enter: deep_sleep_1
#    turn_off_action:
#      - deep_sleep.enter: deep_sleep_1

sensor:
  - platform: dht
    pin: GPIO3
    model: DHT22
    temperature:
      id: temperature
      name: "Temperature"
    humidity:
      id: humidity
      name: "Humidity"
    update_interval: 10s
  - platform: adc
    pin: GPIO4
    id: battery
    name: "Battery"
    accuracy_decimals: 2
    update_interval: 10s
    attenuation: 12dB
    samples: 10
    filters:
      - multiply: 2.0  # The voltage divider requires us to multiply by 2

light:
  - platform: status_led
    name: "Status LED"
    id: esp_status_led
    icon: "mdi:alarm-light"
    pin:
      number: GPIO8
      inverted: true
    restore_mode: ALWAYS_OFF

