# this is a simple test device setup that's used to compile and test the examples
esphome:
  name: srs-gcsdspl-01
  build_path: build/srs-gcsdspl-01
  project:
    name: siralab.srs-gcsdspl-01
    version: 1.0.0

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: esp-idf

psram:
  mode: octal
  speed: 80MHz

logger:
  level: DEBUG

api:

ota:
  - platform: esphome

mdns:
  disabled: True

socket:
  implementation: meshmesh_esp32

external_components:
  - source: github://EspMeshMesh/esphome-meshmesh@main
    refresh: 0s

meshmesh:
  baud_rate: 0
  rx_buffer_size: 0
  tx_buffer_size: 0
  password: !secret meshmesh_password
  channel: 3
  use_starpath: True
  node_type: edge

time:
  - platform: pcf85063
    id: pcf85063_time

uart:
  id: uart_goldelox
  tx_pin: 43
  rx_pin: 44
  baud_rate: 9600

output:
  - platform: ledc
    id: gpio_15
    pin: 15
  - platform: ledc
    pin: 42
    id: rtttl_out

light:
  - platform: monochromatic
    output: gpio_15
    id: backlight
    restore_mode: RESTORE_DEFAULT_ON

spi:
  id: spi_display
  interface: hardware
  clk_pin: 6
  mosi_pin: 7

i2c:
  id: i2c_bus
  sda: 11
  scl: 10
  scan: false
  
spi_device:
  - id: spidev
    data_rate: 40MHz

display:
  - platform: mipi_spi
    update_interval: 25ms
    model: ST7789V
    dc_pin: 4
    cs_pin: 5
    reset_pin: 8
    invert_colors: true
    dimensions:
      width: 320
      height: 240
      offset_width: 0
    transform:
      swap_xy: true
      mirror_x: false
      mirror_y: true

packages:
  - !include lvgl_small_display.yaml

lvgl:

rtttl:
  output: rtttl_out
  on_finished_playback:
    - logger.log: 'Song ended!'

interval:
  - interval: 60min
    startup_delay: 2sec
    then:
      - rtttl.play: 'two_short:d=4,o=5,b=100:16e6,16e6'
