---
substitutions:
  switch_name: Switch
  binary_sensor_name: Button

external_components:
#  - source: github://persuader72/esphome-components@master
#    components: [ shelly_dallas ]
  - source: /home/stefano/Sviluppo/Stefano/esphome-components/components
    components: [ shelly ]

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_160: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ: "160"

packages:
  base: !include common-base.yaml
  meshmesh: !include ../common/meshmesh.yaml

switch:
  - platform: gpio
    id: switch_1
    name: ${switch_name}
    pin: GPIO26

binary_sensor:
  - platform: gpio
    name: "${device_name} Switch"
    pin: GPIO4
    on_press:
      then:
        - switch.toggle: "relay"
    filters:
      - delayed_on_off: 50ms
  - platform: gpio
    name: "${device_name} Button"
    pin:
      number: GPIO25
      inverted: yes
      mode:
        input: true
        pullup: true
    on_press:
      then:
        - switch.toggle: "relay"
    filters:
      - delayed_on_off: 5ms

sensor:
  - platform: ntc
    sensor: temp_resistance_reading
    name: "Internal Temperature"
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
    on_value_range:
      - above: "80.0"
        then:
          - switch.turn_off: "relay"
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 10kOhm
  - platform: adc
    id: temp_analog_reading
    pin: GPIO32
    attenuation: 12db
  - platform: adc
    name: "${device_name} Relay Supply Voltage"
    pin: GPIO33
    attenuation: 12db
    filters:
      - multiply: 8
#  - platform: shelly_dallas
#    index: 0
#    name: "External Temperature1"
#    unit_of_measurement: "°C"
#    accuracy_decimals: 1
#    icon: "mdi:thermometer"
#  - platform: shelly_dallas
#    index: 1
#    name: "External Temperature2"
#    unit_of_measurement: "°C"
#    accuracy_decimals: 1
#    icon: "mdi:thermometer"
  - platform: dallas_temp
#    address: 0x1234567812345628
    name: temperature
    update_interval: 120s
#  - platform: shelly_dht
#    pin_a: GPIO1
#    pin_b: GPIO0
#    temperature:
#      name: "Living Room Temperature"
#    humidity:
#      name: "Living Room Humidity"
#    update_interval: 60s 