---
substitutions:
  switch_name: Switch
  switch_id: switch_1
  switch_is_internal: false
  binary_sensor_name: Button

packages:
  common: !include ../common-esp8266.yaml
  meshmesh: !include ../common/meshmesh.yaml

switch:
  - platform: gpio
    id: ${switch_id}
    name: ${switch_name}
    pin: GPIO4
    internal: ${switch_is_internal}

binary_sensor:
  - platform: gpio
    id: binary_sensor_1
    name: ${binary_sensor_name}
    pin: GPIO5                    
