---
substitutions:
  temperature_id: temperature
  temperature_name: Temperature
  humidity_id: humidity
  humidity_name: Humidity
  update_interval: 120s

external_components:
  - source: github://persuader72/esphome-components@master
    components: [ shelly ]

one_wire:
  - platform: shelly
    input: GPIO1
    output: GPIO0

sensor:
  - platform: dallas_temp
    name: ${temperature_name}
    id: ${temperature_id}
    update_interval: 120s
